### ISSUE TITLE
Front end UI Design

### ISSUE THREAD

**Issue by tobias-g1** [nicholas-2/engine-steem#3]
I saw in your announcement post that you're looking to build an interface, and think it would be an interesting project to get involved in. I'd be interested in helping put together a design for it if that would be useful?

I don't have much of a portfolio, as a lot of the design work I have done in the past is closed source, but my latest work on Utopian can be found here:

https://busy.org/@tobias-g/redesign-fpl-plus-chrome-extension-pop-up-ui

I also created https://contesthero.io if that offers any guidance. 

Let me know your thoughts :)

**Comment by tobias-g1** [comment]
I'll join tomorrow and we can discuss further, I'd prefer initially submit a UI design so we can iterate and I completely understand what is needed and from there we can look at developing it if that's ok? Should get a more polished product at the end of it too.

**Comment by nicholas-2** [comment]
Great! Ill see you on the Discord!

**Comment by tobias-g1** [comment]
My bad, I did click on the link yesterday and it's expired and forgot to go find it on Steem. If you could send a new link that would be great.
